on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: Updates Unsplash stats and blog posts

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Updating blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: BLOG
          commit_message: "Updated feed with the latest dav.to data"
          feed_list: "https://dev.to/feed/bernardo"
